[versions]
bcrypt = "0.10.2"
coroutines = "1.10.2"
exposed = "1.3.1"
h2 = "2.4.240"
h2-r2dbc = "1.1.0.RELEASE"
hikaricp = "7.0.2"
koin = "4.2.2"
kotest = "5.9.1"
ktor = "3.5.2"
kotlin = "2.4.0"
logback = "1.5.37"
mockk = "1.14.5"
postgresql = "42.7.13"
prometheus = "1.17.0"

[libraries]
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-javaTime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
h2database-h2 = { module = "com.h2database:h2", version.ref = "h2" }
h2database-r2dbc = { module = "io.r2dbc:r2dbc-h2", version.ref = "h2-r2dbc" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-loggerSlf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
ktor-serverRoutingOpenapi = { module = "io.ktor:ktor-server-routing-openapi", version.ref = "ktor" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micrometer-registryPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheus" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
